version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YourStrong@Passw0rd
      - MYSQL_DATABASE=BlogDb
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collaborativeblog_app
    ports:
      - "5000:80"
    networks:
      - backend

volumes:
  mysqldata:

networks:
  backend:
